services:
  stockDock-psql:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=psql-stockDock
      - POSTGRES_PASSWORD=stockpsql
    volumes:
      - ./1-investments-database.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4:9.3.0
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=web@ufop.edu.br
      - PGADMIN_DEFAULT_PASSWORD=pgmaster
    networks:
      - backend

networks:
  backend: